### ISSUE TITLE
macOS run error

### ISSUE THREAD

**Issue by jianshu93** [AndreLamurias/GraphMB#13]
Hello GraphMB team,

It seems when running on MacOS, it stopped at printing PyTorch and never stops:

Jianshus-MBP-3:data jianshuzhao$ graphmb --assembly ./strong100/ --outdir results_graphmb --numcores 2
pytorch
setting seed to 1
logging to results_graphmb/20220726-233243_output.log
Running GraphMB 0.1.5
using cuda: False
cuda available: False , using  cpu
processing sequences ./strong100/assembly.fasta
read 1150 seqs
processing GFA file ./strong100/assembly_graph.gfa
skipped contigs 23 < 1000
read 1270 edges
creating DGL graph
done
connected components...
636 connected
saving graph results_graphmb/cached_min1000_kmer4/train_info.pkl
Abundance dim: 1
using these batchsteps: [25, 75, 150, 300]
running VAMB...
pytorch
pytorch
pytorch
pytorch
pytorch
pytorch
pytorch
pytorch
pytorch
...

It seems PyTorch on MacOS for vamb is not supported well.

Thanks,

Jianshu

**Comment by AndreLamurias** [comment]
Hi Jianshu, I recommend that you use the docker version, we don't have a way to support macOS. If the docker version doesn't work, open another issue.

**Comment by jianshu93** [comment]
Thanks！ by the way what is the status of VAEG-BIN？ I love both of those ideas and cannot wait to play/test it！ GCN self-supervized classification seems more natural than graph embedding + VAE + clustering. Great work！


Jianshu
