### ISSUE TITLE
GraphMB for short-read sequencing

### ISSUE THREAD

**Issue by dtx282000** [AndreLamurias/GraphMB#15]
Thank you for your perfect GraphMB.
I want to know if this software can be used for the short-read sequencing data? 
Thanks!

**Comment by AndreLamurias** [comment]
Hi, thanks for the interest, it should run on short-reads even though we mostly tested it on long reads, so on short-reads the improvements will be limited. this is because the assembly graph of a short read assembly is much more complex.
