### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by tnn111** [AndreLamurias/GraphMB#16]
I am getting an error I do not understand. Any thoughts? It is a large dataset; over 100,000 contigs.

Thanks!

(graphmb) [torben@monkster results_flye_m4000_00]$ /usr/bin/time graphmb --assembly graphmb --numcores 32 2> graphmb.log &
[1] 2357447
(graphmb) [torben@monkster results_flye_m4000_00]$ pytorch
setting seed to 1
logging to graphmb/20221106-231235_output.log
Running GraphMB 0.1.5
using cuda: False
cuda available: False , using  cpu
processing sequences graphmb/assembly.fasta
read 107977 seqs
processing GFA file graphmb/assembly_graph.gfa
skipped contigs 132102 < 1000
read 0 edges
creating DGL graph
done
connected components...
0 connected
saving graph graphmb/cached_min1000_kmer4/train_info.pkl
Uncaught exception
Traceback (most recent call last):
  File "/home/torben/opt/mambaforge/envs/graphmb/bin/graphmb", line 8, in <module>
    sys.exit(main())
  File "/home/torben/opt/mambaforge/envs/graphmb/lib/python3.7/site-packages/graphmb/main.py", line 226, in main
    logging.debug("Abundance dim: {}".format(len(dataset.nodes_depths[0])))
IndexError: list index out of range

[1]+  Exit 1                  /usr/bin/time graphmb --assembly graphmb --numcores 32 2> graphmb.log

**Comment by AndreLamurias** [comment]
Hi, seems like it skipped all of your nodes/contigs so the graph was empty. 
Did you follow the pre-processing instructions in the README file? If not, the assembly.fasta file will contain contig sequences, while GraphMB is expecting edge sequences. Then you have to use the "--contignodes" option or extract the edge sequences from the GFA file to a fasta file. You also got an error reading the jgi depth file, what are the contents of your graphmb/assembly_depth.txt file? (the first few lines)
