### ISSUE TITLE
Memory problems with batches - up to 800 GB RAM used

### ISSUE THREAD

**Issue by caity-s** [AndreLamurias/GraphMB#20]
Hey André,

Great tool! We are testing it out with some anaerobic digester data, and 17 work well but 3 of the samples are failing. We are using the latest conda release, and it is all preprocessed following Mantas' mmlong2 workflow. 

Mantas said it could be to do with long contigs in the batch size, which may make sense as the samples are less diverse that activated sludge, smaller assemblies (0.8 to 1.2 Gbp assemblies) but perhaps have more strain heterogeneity. The samples that failed got up to 500, 600 and 800 GB RAM before being killed. I am running with 40 threads on a 876 GB RAM server. Note I was running them in -j2 parallel as the other 15 ish samples had max RAM usage of 100-250 GB.

```
NNF_AD18_3.log:/projects/microflora_danica/mmlong2/mmlong2: line 999: 195213 Killed                  graphmb --assembly $dir_work/tmp/binning --outdir $dir_work/tmp/binning/graphmb --assembly_name contigs_lin_filt_ord.fasta --depth metabat_cov.tsv --contignodes --numcores $threads --assembly_type flye
NNF_AD19_3.log:/projects/microflora_danica/mmlong2/mmlong2: line 999: 1773840 Killed                  graphmb --assembly $dir_work/tmp/binning --outdir $dir_work/tmp/binning/graphmb --assembly_name contigs_lin_filt_ord.fasta --depth metabat_cov.tsv --contignodes --numcores $threads --assembly_type flye
```

I have attached the logs for the 3 samples so you can see where they failed. I will try rerunning on the 1024 GB RAM server to see if they will process successfully there too.

[20230201-004310_output.log](https://github.com/MicrobialDarkMatter/GraphMB/files/10792020/20230201-004310_output.log)
[20230215-065342_output.log](https://github.com/MicrobialDarkMatter/GraphMB/files/10792021/20230215-065342_output.log)
[20230218-082341_output.log](https://github.com/MicrobialDarkMatter/GraphMB/files/10792022/20230218-082341_output.log)

What do you think?

Thanks a lot :) 
Caitlin

**Comment by caity-s** [comment]
Just something interesting - AD18 is a 0.8 Gbp assembly, but 0.35 Gbp is all one assembly graph hairball...

**Comment by AndreLamurias** [comment]
Hi Caitlin,
I have to update the conda release, it seems like it hasn't been updated to 0.2. That could bring some improvements. But the hairball that you mentioned could be the source of problems. I also haven't tested with the --contignodes option that much, so maybe something could be improved about that, maybe the generated contig graph has too many edges. 
Either way the new version should give more info about that. I'll let you know once the conda release has been updated.

**Comment by AndreLamurias** [comment]
actually can you just try updating graphmb inside conda? 
`pip install --upgrade graphmb`

**Comment by caity-s** [comment]
Thanks André, I will give it ago when I have a moment and update you :) Yes, a few of the edges have 2-3000 connections...
