### ISSUE TITLE
AttributeError

### ISSUE THREAD

**Issue by cyanoluu** [AndreLamurias/GraphMB#22]
Hi,

I would like to ask you for help. In try to use the same command that is showed in README:

graphmb --assembly data/strong100/ --outdir results/strong100/ --assembly_name contigs.fasta --depth contig_depth.txt --contignodes --markers ""

Of course, adjusted to my data directories and files. I got this error:

Assembly Graph file assembly_graph.gfa not found, check --graph_file option
logging to met20_graphMB/20230308-210533graphmb_output.log
Running GraphMB 0.2.3
using cuda: False
setting seed to 1
setting tf seed
Reading cache from
==============================
DATASET STATS:
number of sequences: 59145
assembly length: 1.073 Gb
assembly N50: 0.044 Mb
assembly average length (Mb): 0.018 max: 6.389 min: 0.0
coverage samples: 1
No assembly graph loaded
No SCG markers
==============================
==============Running VAE model=====================
setting tf seed
Uncaught exception
Traceback (most recent call last):
  File "/home/sehnal/miniconda3/envs/graphmb/bin/graphmb", line 8, in <module>
    sys.exit(main())
  File "/home/sehnal/miniconda3/envs/graphmb/lib/python3.9/site-packages/graphmb/main.py", line 497, in main
    vae_embs, _ = train_ccvae.run_model_ccvae(dataset, args, logger, 0,
  File "/home/sehnal/miniconda3/envs/graphmb/lib/python3.9/site-packages/graphmb/train_ccvae.py", line 154, in run_model_ccvae
    X, adj, cluster_mask, neg_pair_idx, pos_pair_idx = prepare_data_for_gnn(
  File "/home/sehnal/miniconda3/envs/graphmb/lib/python3.9/site-packages/graphmb/train_ccvae.py", line 53, in prepare_data_for_gnn
    adj_matrix = dataset.adj_matrix.copy()
AttributeError: 'NoneType' object has no attribute 'copy'

Do you have any tip how to fix this error?

**Comment by AndreLamurias** [comment]
Hi, as it says, GraphMB could not find the graph file which is necessary. You can point to it with   "--graph_file" if it's not in data/strong100/
