### ISSUE TITLE
no bins produced

### ISSUE THREAD

**Issue by soklidahong** [AndreLamurias/GraphMB#23]
Thank you for developing the tool. I was running graphmb and looked find but there were no bins produced.

graphmb --assembly binning/round_1 --outdir binning/round_1/graphmb --assembly_name contigs_lin.fasta --graph_file assembly_graph.gfa --depth metabat_cov_filt.tsv --markers "" --contignodes --numcores 28 --assembly_type flye --minbin 250000 --mincontig 4000
logging to binning/round_1/graphmb/20230309-163709graphmb_output.log
Running GraphMB 0.2.3
using cuda: False
setting seed to 1
setting tf seed
Cache not found on binning/round_1/graphmb
processing sequences binning/round_1/contigs_lin.fasta
read 12535 seqs
processing GFA file (contig nodes) binning/round_1/assembly_graph.gfa
skipped contigs 0 < 4000
read 13671, edges
reading depths
reading labels
Saved cache to binning/round_1/graphmb

==============================
DATASET STATS:
number of sequences: 12535
assembly length: 0.921 Gb
assembly N50: 0.194 Mb
assembly average length (Mb): 0.073 max: 5.846 min: 0.004
coverage samples: 1
Graph file found and read
graph edges: 13671
contig paths: 12535
No SCG markers
==============================
==============Running VAE model=====================
setting tf seed
edges with overlapping scgs (max=20): []
deleted 0 edges with same SCGs
**** Num of edges: 18181
******* Running model: CCVAE **********
***** using edge weights: True ******
***** cluster markers only: False *****
***** self edges only: False *****
***** Using raw kmer+abund features: True
***** SCG neg pairs: (0,)
***** input features dimension: (12535, 104)
>>> Pre train stats: {'precision': 1.0, 'recall': 0.3901076984443558, 'f1': 0.5612625538020086, 'ari': 0, 'hq': 0, 'mq': 0, 'n_clusters': 1372, 'unresolved_mags': 0}
*** Model input dim 104, GNN input dim 64
use_ae: True, run AE only: False output clustering dim 64
  0%|                                                                                           | 0/500 [00:00<?, ?it/s]**** initial nodes batch size: 256 ****
**** epoch batch size doubles: [25, 75, 150, 300] ****
[ccvae ] Total=0.082 kld=0.008 vae=0.082 kmer=0.022 ab=0.052 Bestnoeval=0 BestEpoch=0 Curnoeval=0 GPU=0.0MB:   5%| | 25/Increasing nodes batch size from 256 to 512
[ccvae ] Total=0.057 kld=0.006 vae=0.057 kmer=0.018 ab=0.033 Bestnoeval=0 BestEpoch=0 Curnoeval=0 GPU=0.0MB:  15%|▏| 75/Increasing nodes batch size from 512 to 1024
[ccvae ] Total=0.042 kld=0.005 vae=0.042 kmer=0.017 ab=0.021 Bestnoeval=0 BestEpoch=0 Curnoeval=0 GPU=0.0MB:  30%|▎| 150Increasing nodes batch size from 1024 to 2048
[ccvae ] Total=0.035 kld=0.003 vae=0.035 kmer=0.015 ab=0.017 Bestnoeval=0 BestEpoch=0 Curnoeval=0 GPU=0.0MB:  60%|▌| 300Increasing nodes batch size from 2048 to 4096
[ccvae ] Total=0.026 kld=0.002 vae=0.026 kmer=0.014 ab=0.009 Bestnoeval=0 BestEpoch=0 Curnoeval=0 GPU=0.0MB: 100%|█| 500>>> Last epoch: 0 : {'precision': 1.0, 'recall': 0.020741922616673316, 'f1': 0.04064087534193044, 'ari': 0, 'hq': 0, 'mq': 0, 'n_clusters': 5175, 'unresolved_mags': 0, 'epoch': 499} <<<
>>> best epoch: 0 : {'precision': 1.0, 'recall': 0.020741922616673316, 'f1': 0.04064087534193044, 'ari': 0, 'hq': 0, 'mq': 0, 'n_clusters': 5175, 'unresolved_mags': 0, 'epoch': 499} <<<
===================================================
writing features to binning/round_1/features.tsv
RUN 0
setting torch seed
setting tf seed
edges with overlapping scgs (max=20): []
deleted 0 edges with same SCGs
**** Num of edges: 18181
logging to mlflow
******* Running model: gcn **********
***** using edge weights: True ******
***** using disconnected: True ******
***** concat features: True *****
***** cluster markers only: False *****
***** threshold adj matrix: False *****
***** self edges only: False *****
***** Using raw kmer+abund features: False
***** SCG neg pairs: (0,)
***** input features dimension: 64
***** Nodes used for clustering: 12535
>>> Pre train stats: {'precision': 1.0, 'recall': 0.020741922616673316, 'f1': 0.04064087534193044, 'ari': 0, 'hq': 0, 'mq': 0, 'n_clusters': 5282, 'unresolved_mags': 0}
*** Model input dim 64, GNN input dim 64
*** output clustering dim 32
[graphmb 3l] L=0.663 D=0.000  GPU=0.0MB: 100%|████████████████████████████████████████| 500/500 [01:46<00:00,  4.68it/s]>>> best epoch all contigs: 0 : {'precision': 1.0, 'recall': 0.012764260071798962, 'f1': 0.02520677432059866, 'ari': 0, 'hq': 0, 'mq': 0, 'n_clusters': 5314, 'unresolved_mags': 0, 'epoch': 499} <<<
>>> best epoch: 0 : {'precision': 1.0, 'recall': 0.012764260071798962, 'f1': 0.02520677432059866, 'ari': 0, 'hq': 0, 'mq': 0, 'n_clusters': 5314, 'unresolved_mags': 0, 'epoch': 499} <<<
### writing best and last embs to binning/round_1/graphmb
setting torch seed
setting tf seed
### epoch: 499.000 0.000
0.0 0.0 0.0 0.0
Total run time: 0:17:18.157562
Seconds per run: 1038.16

**Comment by AndreLamurias** [comment]
Hi, you can find a file mapping each contig to a bin in your outdir binning/round_1/graphmb
We can add an option to write the bins directly to fasta. In the meanwhile you can use this script to do the same things: https://github.com/AndreLamurias/binning_workflows/blob/main/write_fasta_bins.py

**Comment by soklidahong** [comment]
It worked. Thanks!
