### ISSUE TITLE
error "ModuleNotFoundError: No module named 'graphmb.data'"

### ISSUE THREAD

**Issue by chiaramazzoni** [AndreLamurias/GraphMB#26]
Hi, 

I get this error at launch `ModuleNotFoundError: No module named 'graphmb.data'` after having installed the tool from source with pip. Is my installation missing something?

**Comment by Montmerry** [comment]
Hi, 

I have the same error. Does anyone know the reason?

**Comment by AndreLamurias** [comment]
sorry, I'm a bit swamped with work. Can you give me more details, are you using a virtual environment? which OS are you using? Can you install from pypi (instead of installing from source)?

**Comment by AndreLamurias** [comment]
a quick fix is to create this directory: "src/graphmb/data" and move "data/Bacteria.ms" and "data/kernel.npz" to there. I'll push a better fix soon
