### ISSUE TITLE
Negative edges in neighborhoods

### ISSUE THREAD

**Issue by yamada321** [AndreLamurias/GraphMB#27]
Hi, 

Thank you for the wonderful tool.  I wonder how does GraphMB handle not fully phased or cleaned regions in a given assembly graph. For example, during the neighborhood sampling and graph embedding, from my understanding, GraphMB will not try to split edges of a simple bubble apart. Intuitively, if they also unfortunately share similar read coverage, this might lead to a contaminated bin. Does this happen in practice, or GraphMB's algorithm already has mitigations? 

In binning of phased long read assemblies, I see many contaminated bins (from other binners as well). I'm trying to figure out why and if there's anything could be done.

Thank you!

**Comment by AndreLamurias** [comment]
Hi, sorry for the delayed response. GraphMB takes the assembly graph as it is, and it does not try to fix any assembly issues. So, as you said, yes, this can be a source of contamination.
