### ISSUE TITLE
No Bins are generated - not even with the write_fasta_bins.py script

### ISSUE THREAD

**Issue by alegarritano** [AndreLamurias/GraphMB#29]
**Describe the bug**
Hi,

I've installed GraphMB from source copying the data folder to /src/graphmb and the installation seemed to be working fine. I proceeded to bin my assembly (Flye v2.9.2) with the following command:

graphmb --assembly /path/to/folder/with/all/files --outdir /path/to/outdir --marker "" --cuda --post writebins

However, no bins were generated. I reran the software by removing the --post flag and tried to use the write_fasta_bins.py script  to generate the bins. I downloaded the script from https://github.com/AndreLamurias/binning_workflows/blob/main/write_fasta_bins.py since the file is not in the /src folder.
I used the graphmb_0_best_contig2bin.tsv  and my original .fasta file as inputs for the script.

However, I am getting a parsing error: 

contig_name, bin_name = line.strip().split("\t")
ValueError: not enough values to unpack (expected 2, got 1)

The generated TSV file has 2 columns separated by a \t and initially I thought it could be an empty line at the end of the tsv file, but I removed it and it's still not working. Can you please let me know how to solve this? 

Thanks

**Comment by AndreLamurias** [comment]
Hi, can you share the generated graphmb_0_best_contig2bin.tsv file?
It's strange that it is not writing bin files, I will check that later. But if the tsv file was generated, that script should be able to read it.

**Comment by alegarritano** [comment]
Hi Andre, thanks for getting back to me.

I can't share TSV files on github, so I compressed it. Please, find it attached.
Cheers,
[graphmb_0_best_contig2bin.tsv.zip](https://github.com/MicrobialDarkMatter/GraphMB/files/12074438/graphmb_0_best_contig2bin.tsv.zip)

**Comment by AndreLamurias** [comment]
The issue was the headers. The write_fasta_bins.py file did not account for the fact that the output files have header lines (starting with @) to make it compatible with AMBER. I have fixed that file, but you can also delete those lines, and it should work. let me know if you still have issues with that. I'm also going to add a "--writebins" option to GraphMB to make it easier.

**Comment by alegarritano** [comment]
Hi Andre,
I tried removing all the header lines before and it still didn't work. I had a different error instead. Regardless, the new script is working like a charm. Thanks for that.
