### ISSUE TITLE
--vamb is mentioned in README

### ISSUE THREAD

**Issue by granek** [AndreLamurias/GraphMB#31]
In the README you mention the --vamb command line options, but it is not available in the current version of GraphMB
https://github.com/MicrobialDarkMatter/GraphMB/blob/38926dfce620f6a7472c9f446e196b5cf5faa4c8/README.md?plain=1#L83

**Comment by AndreLamurias** [comment]
Yes this option was deprecated when we implemented our own VAE. But for testing purposes, you can still use VAMB embeddings with the "--features" and my fork of VAMB: https://github.com/andrelamurias/vamb since I think they have not implemented an option to write the embeddings to a file.
