### ISSUE TITLE
ValueError running graphmb

### ISSUE THREAD

**Issue by harrytchild** [AndreLamurias/GraphMB#32]
HI,

I am encountering an ValueError when running GraphMB.

I have pasted the output from the command including the error below. Any help solving this issue would be much appreciated.

Cheers,

Harry

$ nohup graphmb    --assembly /localdata/harry/MAF013/mag_assembly/metaflye_assemblies/graphmb_ont_pipeline    --outdir graphmb_results/    --assembly_name polished.fasta    --graph_file assembly_graph.gfa    --depth polished_depth.txt    > graphmb.out &

cat graphmb.out 
logging to graphmb_results/20231018-170333graphmb_output.log
Running GraphMB 0.2.5
using cuda: False
setting seed to 1
setting tf seed
Cache not found on graphmb_results/
processing sequences /localdata/harry/MAF013/mag_assembly/metaflye_assemblies/graphmb_ont_pipeline/polished.fasta
read 58526 seqs
processing GFA file (edge nodes) /localdata/harry/MAF013/mag_assembly/metaflye_assemblies/graphmb_ont_pipeline/assembly_graph.gfa
skipped contigs 522 < 1000
read 3853, edges
reading depths
reading labels
Saved cache to graphmb_results/

Not using SCG file: marker_gene_stats.tsv (not found)
==============================
DATASET STATS:
number of sequences: 58526
assembly length: 0.502 Gb
assembly N50: 0.011 Mb
assembly average length (Mb): 0.009 max: 1.696 min: 0.001
coverage samples: 1
Graph file found and read
graph edges: 3853
contig paths: 58719
No SCG markers
==============================
==============Running VAE model=====================
setting tf seed
edges with overlapping scgs (max=20): []
deleted 0 edges with same SCGs
**** Num of edges: 62068
******* Running model: CCVAE **********
***** using edge weights: True ******
***** cluster markers only: False *****
***** self edges only: False *****
***** Using raw kmer+abund features: True
***** SCG neg pairs: (0,)
***** input features dimension: (58526, 104)
>>> Pre train stats: {'precision': 1.0, 'recall': 0.02417728872637802, 'f1': 0.04721309287466008, 'ari': 0, 'hq': 0, 'mq': 0, 'n_clusters': 48740, 'unresolved_mags': 0}
*** Model input dim 104, GNN input dim 64
use_ae: True, run AE only: False output clustering dim 64
  0%|          | 0/500 [00:00<?, ?it/s]**** initial nodes batch size: 256 ****
**** epoch batch size doubles: [25, 75, 150, 300] ****
[ccvae ] Total=0.064 kld=0.003 vae=0.064 kmer=0.041 ab=0.020 Bestnoeval=0 BestEpoch=0 Curnoeval=0 GPU=0.0MB: 100%|██████████| 500/500 [42:21<00:00,  5.08s/it]Increasing nodes batch size from 256 to 512
Increasing nodes batch size from 512 to 1024
Increasing nodes batch size from 1024 to 2048
Increasing nodes batch size from 2048 to 4096
>>> Last epoch: 0 : {'precision': 1.0, 'recall': 0.0361036120698493, 'f1': 0.0696911228747176, 'ari': 0, 'hq': 0, 'mq': 0, 'n_clusters': 21558, 'unresolved_mags': 0, 'epoch': 499} <<<
>>> best epoch: 0 : {'precision': 1.0, 'recall': 0.0361036120698493, 'f1': 0.0696911228747176, 'ari': 0, 'hq': 0, 'mq': 0, 'n_clusters': 21558, 'unresolved_mags': 0, 'epoch': 499} <<<

Uncaught exception
Traceback (most recent call last):
  File "/home/harry/miniconda3/envs/graphmb/bin/graphmb", line 8, in <module>
    sys.exit(main())
  File "/home/harry/miniconda3/envs/graphmb/lib/python3.8/site-packages/graphmb/main.py", line 499, in main
    vae_embs, _ = train_ccvae.run_model_ccvae(dataset, args, logger, 0,
ValueError: too many values to unpack (expected 2)

**Comment by palomo11** [comment]
I have the same issue "ValueError: too many values to unpack (expected 2)" @harrytchild were you able to solve it?

**Comment by harrytchild** [comment]
> I have the same issue "ValueError: too many values to unpack (expected 2)" @harrytchild were you able to solve it?

Not yet, sorry

**Comment by palomo11** [comment]
Okay. Hopefully @AndreLamurias or @Abusagit can give us some hints.

**Comment by AndreLamurias** [comment]
If you're running from source, you can modify line 499 from main.py to expect three arguments (vae_embs, _ , _= train_ccvae.run_model_ccvae), that should be enough, I am testing it just now. You can also modify directly in your installation for a quick fix (/home/harry/miniconda3/envs/graphmb/lib/python3.8/site-packages/graphmb/main.py)
I am fixing the pypi and docker options this week for a more permanent solution.

**Comment by palomo11** [comment]
Thanks @AndreLamurias . That modification has solved the issue, however, I have encountered another error (I have opened a new different issue #33 )

**Comment by jianshu93** [comment]
Hi @AndreLamurias, can you please publish a new version on pypi so that the error is not here if directly install via pip. Thanks! Jianshu
