### ISSUE TITLE
"best epoch all contigs" or "best epoch"？

### ISSUE THREAD

**Issue by avery-k** [AndreLamurias/GraphMB#34]
Dear Mr. Lamurias,
My run instructions and output are shown in the figure1 and figure2, I wonder why I should refer to the output of "best epoch all contigs" or the output of "best epoch"? If it is the output of the best epoch, why is my value so low? I tried to send an email to you by email, hoping to get your help, but failed to send it. I would be very grateful if you could spare some time to help me.
![Figure1](https://github.com/MicrobialDarkMatter/GraphMB/assets/61675489/bd4202a9-ded2-4667-bfbb-e954ae7cb4ca)
![Figure2](https://github.com/MicrobialDarkMatter/GraphMB/assets/61675489/9dafd3e0-2228-49e7-8a4d-f85805af1ac4)

**Comment by AndreLamurias** [comment]
Hi avery-k,
you probably sent to my AAU email which is disabled because I don't work there anymore. I can't see you picture, the resolution is too low. Can you copy paste the results you're obtaining and what data you are using?

**Comment by avery-k** [comment]
ok，thank you for helping me, mr. Lamurias. I used the strong100 dataset.
my commands：python src/graphmb/main.py --assembly data/strong100/ --outdir results/strong100/ --evalskip 100 \
    --epoch 1000  --model gcn --rawfeatures --batchsize 256   \
   --ae_alpha 1 --scg_alpha 0 --lr_gnn 1e-3 --layers_gnn 0 --negatives 0  \
   --outname vae_lr1e-3_bs256 --nruns 3  \
   --embsize_gnn 32 --quick
my log result：Running GraphMB 0.2.5
using cuda: False
setting seed to 1
Reading cache from
RUN 0
******* Running model: gcn **********
***** using edge weights: True ******
***** using disconnected: False ******
***** concat features: True *****
***** cluster markers only: True *****
***** threshold adj matrix: False *****
***** self edges only: False *****
***** Using raw kmer+abund features: True
***** SCG neg pairs: (8799, 2)
***** input features dimension: 104
***** Nodes used for clustering: 215
>>> Pre train stats: {'precision': 1.0, 'recall': 0.04695652173913043, 'f1': 0.08970099667774087, 'ari': 0, 'hq': 22, 'mq': 25, 'n_clusters': 48, 'unresolved_mags': 17, 'hq_comp': 98.35636933599316, 'hq_cont': 0.3134796238244514, 'unresolved_contigs': 172, 'unresolved_contigs_with_scgs': 172}
*** Model input dim 104, GNN input dim 104
*** output clustering dim 32
>>> best epoch all contigs: 40 : {'precision': 1.0, 'recall': 0.3269565217391304, 'f1': 0.49279161205766714, 'ari': 0, 'hq': 17, 'mq': 19, 'n_clusters': 380, 'unresolved_mags': 22, 'hq_comp': 98.46026184768577, 'hq_cont': 0.30425963488843816, 'unresolved_contigs': 1113, 'unresolved_contigs_with_scgs': 187, 'epoch': 999} <<<
>>> best epoch: 40 : {'precision': 1.0, 'recall': 0.04695652173913043, 'f1': 0.08970099667774087, 'ari': 0, 'hq': 27, 'mq': 31, 'n_clusters': 50, 'unresolved_mags': 12, 'hq_comp': 98.46336932543828, 'hq_cont': 0.2554278416347382, 'unresolved_contigs': 162, 'unresolved_contigs_with_scgs': 162, 'epoch': 139} <<<
### writing best and last embs to /home/chenli/code/graphmb/GraphMB/src/strong100/feature1/
RUN 1
*** Model input dim 104, GNN input dim 104
*** output clustering dim 32
>>> best epoch all contigs: 120 : {'precision': 1.0, 'recall': 0.26521739130434785, 'f1': 0.41924398625429554, 'ari': 0, 'hq': 17, 'mq': 19, 'n_clusters': 375, 'unresolved_mags': 22, 'hq_comp': 98.35884196938963, 'hq_cont': 0.30425963488843816, 'unresolved_contigs': 1113, 'unresolved_contigs_with_scgs': 186, 'epoch': 999} <<<
>>> best epoch: 120 : {'precision': 1.0, 'recall': 0.028695652173913042, 'f1': 0.055790363482671176, 'ari': 0, 'hq': 29, 'mq': 33, 'n_clusters': 51, 'unresolved_mags': 10, 'hq_comp': 98.33153172629986, 'hq_cont': 0.29726516052318663, 'unresolved_contigs': 139, 'unresolved_contigs_with_scgs': 139, 'epoch': 219} <<<
### writing best and last embs to /home/chenli/code/graphmb/GraphMB/src/strong100/feature1/
RUN 2
*** Model input dim 104, GNN input dim 104
*** output clustering dim 32
>>> best epoch all contigs: 320 : {'precision': 1.0, 'recall': 0.27391304347826084, 'f1': 0.4300341296928327, 'ari': 0, 'hq': 16, 'mq': 17, 'n_clusters': 383, 'unresolved_mags': 23, 'hq_comp': 98.25626959247649, 'hq_cont': 0.3232758620689655, 'unresolved_contigs': 1100, 'unresolved_contigs_with_scgs': 175, 'epoch': 999} <<<
>>> best epoch: 320 : {'precision': 1.0, 'recall': 0.026956521739130435, 'f1': 0.05249788314987299, 'ari': 0, 'hq': 27, 'mq': 28, 'n_clusters': 53, 'unresolved_mags': 12, 'hq_comp': 98.14408452339485, 'hq_cont': 0.3192848020434227, 'unresolved_contigs': 130, 'unresolved_contigs_with_scgs': 130, 'epoch': 419} <<<
### writing best and last embs to /home/chenli/code/graphmb/GraphMB/src/strong100/feature1/
### precision: 1.000 0.000
### recall: 0.034 0.009
### f1: 0.066 0.017
### ari: 0.000 0.000
### hq: 27.667 0.943
### mq: 30.667 2.055
### n_clusters: 51.333 1.247
### unresolved_mags: 11.333 0.943
### hq_comp: 98.313 0.131
### hq_cont: 0.291 0.026
### unresolved_contigs: 143.667 13.474
### unresolved_contigs_with_scgs: 143.667 13.474
### epoch: 259.000 117.757
27.7 0.9 30.7 2.1

**Comment by AndreLamurias** [comment]
Best epoch considers only the contigs where SCGs were identified, while best epoch all contigs considers all contigs. However you can always take the bins of the contigs with SCGs, and then run the binner on the remaining contigs.
