### ISSUE TITLE
Issues with pip install

### ISSUE THREAD

**Issue by elizabethmcd** [AndreLamurias/GraphMB#7]
Hello, 

I'm interested in trying this out with some Nanopore sequencing we have from an anaerobic digestor. I've been having some issues with installing with pip with the Git clone and manual pip installation methods, and I followed the conda instructions and get to the last step running `pip install https://github.com/AndreLamurias/GraphMB/releases/download/v0.1.3/graphmb-0.1.3-py3-none-any.whl` and get this error: 

```
  Downloading https://github.com/AndreLamurias/GraphMB/releases/download/v0.1.3/graphmb-0.1.3-py3-none-any.whl (231 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 231.2/231.2 KB 4.6 MB/s eta 0:00:00
Collecting vamb@ git+git://github.com/AndreLamurias/vamb
  Cloning git://github.com/AndreLamurias/vamb to /tmp/pip-install-glb58klw/vamb_5c2cd84b770f4298819b069a7f54d5d8
  Running command git clone --filter=blob:none --quiet git://github.com/AndreLamurias/vamb /tmp/pip-install-glb58klw/vamb_5c2cd84b770f4298819b069a7f54d5d8
  fatal: remote error:
    The unauthenticated git protocol on port 9418 is no longer supported.
  Please see https://github.blog/2021-09-01-improving-git-protocol-security-github/ for more information.
  error: subprocess-exited-with-error

  × git clone --filter=blob:none --quiet git://github.com/AndreLamurias/vamb /tmp/pip-install-glb58klw/vamb_5c2cd84b770f4298819b069a7f54d5d8 did not run successfully.
  │ exit code: 128
  ╰─> See above for output.

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× git clone --filter=blob:none --quiet git://github.com/AndreLamurias/vamb /tmp/pip-install-glb58klw/vamb_5c2cd84b770f4298819b069a7f54d5d8 did not run successfully.
│ exit code: 128
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```

I'm not sure how to resolve this and was hoping to get some feedback on this. Thanks!

**Comment by AndreLamurias** [comment]
Hi, thanks for the interest :)  the current solution for this error should be:
`git config --global url."git@github.com:".insteadOf git://github.com/`
If you're on a conda environment it should work but let me know if it doesn't. An alternative is to install AndreLamurias/VAMB manually before installing GraphMB. We are trying to eliminate the VAMB dependency in the near future.

**Comment by Abusagit** [comment]
Hi, I've stuck with the same problem recently, and according to the link provided by error message, GitHub blocks every anonymous git clone attempt, so changes has to be done in `setup.py` file and thus new correct `.whl` file should be created, specifically replace query `git+git:/<...>` with `git+https:/<..>`.

I performed this minor change `setup.py` file, run `python3 -m build` in root directory, which generated for me correct wheel, then everything worked after running `pip install .`

I created PR resolving issue for Option 2. For Option 1 solution is to recreate `.whl` file in the provided link using fixed `setup.py`

**Comment by Abusagit** [comment]
@AndreLamurias also I provide new correctly-compiled `.whl` file in my forked repo accessible through this link, this file can be used in new release to replace the older one (I had to create new release by myself, nothing has been changed except `.whl` file), thus installation Option 1 can work correctly now:

[https://github.com/Abusagit/GraphMB/releases/download/v0.1.3.2/graphmb-0.1.3-py3-none-any.whl](https://github.com/Abusagit/GraphMB/releases/download/v0.1.3.2/graphmb-0.1.3-py3-none-any.whl)

Hope this helps ;)

**Comment by AndreLamurias** [comment]
Thanks, that was a better fix than the one I proposed! I will update the wheel and README soon
