### ISSUE TITLE
Typical workflow for GraphMB

### ISSUE THREAD

**Issue by psj1997** [AndreLamurias/GraphMB#9]
Hi,

Thanks for developing this tool.

I want to try your tool in a PacBio data. After reading the document, I am still confused about the preprocessing step. Like `Filter and polish assembly` and `how to generate the assembly graph`.

Can you give me more details about how to generate the inputs? 

Sincerely
Shaojun

**Comment by AndreLamurias** [comment]
Hi Shaojun,
Filtering and polishing the assembly depends on your data, but it might not be necessary if the error rate of your reads is low. The assembly graph is generated with flye. since you have pacbio data instead of nanopore, you have to change the --nano-raw parameter to one of the --pacbio-* params. Then you can follow step 4 in our pre-processing guide.

**Comment by psj1997** [comment]
Thanks for your reply.

After running flye, what I got is:

assembly_graph.gfa,
assembly_graph.gv,
...

Which one is the assembly should be the input?

Sincerely
Shaojun

**Comment by AndreLamurias** [comment]
Hi, it's the .gfa file. You also need to create a fasta file with the edge sequences if you don't have that already:
`awk '/^S/{print ">"$2"\n"$3}' assembly_graph.gfa | fold > edges.fasta`
This part was missing from the readme, I'll add it now.

**Comment by psj1997** [comment]
OK. Thanks for your reply!

**Comment by psj1997** [comment]
Hi, Sorry to bother you again.

I just have another question. You have said that marker_gene_stats.csv can be used in the model training. But I do not find how to generate this file.

Can you give some details? Thanks!

Sincerely
Shaojun

**Comment by AndreLamurias** [comment]
Hi Shaojun,
to generate that file we used CheckM, as in step 4 of the preprocessing guide:
```mkdir edges
cd edges; cat ../assembly.fasta | awk '{ if (substr($0, 1, 1)==">") {filename=(substr($0,2) ".fa")} print $0 > filename }'; cd ..
find edges/ -name "* *" -type f | rename 's/ /_/g'
# evaluate edges
checkm taxonomy_wf -x fa domain Bacteria edges/ checkm_edges/
checkm qa checkm_edges/Bacteria.ms checkm_edges/ -f checkm_edges_polished_results.txt --tab_table -o 2
```

the marker_gene_stats.csv file will be in checkm_edges/storage/

**Comment by psj1997** [comment]
OK. I know. Thank you!

Sincerely
Shaojun
